import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import bcrypt from "bcrypt";
import { resetDatabase, testDatabase } from "../../setup/db.js";

// JWT_SECRET must be present before token.service.ts is imported (it reads the
// env var at module-load time). vi.hoisted runs before any import evaluation.
vi.hoisted(() => {
  vi.stubEnv("JWT_SECRET", "test-jwt-secret-for-integration");
});

import { TokenService } from "../../../src/services/token.service.js";

const port = 3301 + Math.floor(Math.random() * 1000);
const baseUrl = `http://127.0.0.1:${port}`;
const tokenService = new TokenService();

const passwordHash = await bcrypt.hash("password", 12);

// The users.id column is a UUID generated by gen_random_uuid(); non-UUID
// literals like 'user-id-1' are rejected. We let the DB pick the id and
// capture it so we can assert on the token `sub`.
let seededUserId = "";

async function waitForServer(timeoutMs = 10000): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      const response = await fetch(`${baseUrl}/health`);
      if (response.status === 503 || response.status === 200) {
        return;
      }
    } catch {
      // server not ready yet — keep retrying
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error(`Server did not start within ${timeoutMs}ms`);
}

async function seedUser(): Promise<void> {
  const result = await testDatabase.query<{ id: string }>(
    `INSERT INTO users (email, user_name, password_hash, role)
       VALUES ('user@example.com', 'User', $1, 'user')
       RETURNING id`,
    [passwordHash],
  );
  seededUserId = result.rows[0]?.id ?? "";
}

async function login(
  email: string,
  password: string,
): Promise<{ status: number; body: unknown }> {
  const response = await fetch(`${baseUrl}/auth/login`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ email, password }),
  });
  const body = response.status === 204 ? undefined : await response.json();
  return { status: response.status, body };
}

beforeAll(async () => {
  process.env.PORT = String(port);
  process.env.DATABASE_URL =
    process.env.DATABASE_URL_TEST ?? "postgres://postgres:postgres@localhost:5433/quality_test";
  process.env.JWT_SECRET = "test-jwt-secret-for-integration";
  await import("../../../src/server.js");
  await waitForServer();
}, 15000);

afterAll(async () => {
  process.emit("SIGTERM");
  await new Promise((resolve) => setTimeout(resolve, 50));
  await testDatabase.end();
});

beforeEach(async () => {
  await resetDatabase();
  await seedUser();
});

describe("POST /auth/login", () => {
  it("returns 200 with accessToken and refreshToken on valid login", async () => {
    const res = await login("user@example.com", "password");
    expect(res.status).toBe(200);
    expect(res.body).toHaveProperty("accessToken");
    expect(res.body).toHaveProperty("refreshToken");
    expect(typeof (res.body as { accessToken: string }).accessToken).toBe("string");
    expect(typeof (res.body as { refreshToken: string }).refreshToken).toBe("string");
  });

  it("accessToken verifies via TokenService.verifyAccess → { sub, role }", async () => {
    const res = await login("user@example.com", "password");
    const accessToken = (res.body as { accessToken: string }).accessToken;

    const payload = tokenService.verifyAccess(accessToken);
    expect(payload).toMatchObject({ sub: seededUserId, role: "user" });
  });

  it("response body does not contain passwordHash", async () => {
    const res = await login("user@example.com", "password");
    expect(res.body).not.toHaveProperty("passwordHash");
    expect(JSON.stringify(res.body)).not.toContain("passwordHash");
  });

  it("returns 401 invalid_credentials with wrong password", async () => {
    const res = await login("user@example.com", "wrong-password");
    expect(res.status).toBe(401);
    expect(res.body).toEqual({
      error: "invalid_credentials",
      message: "Invalid credentials",
    });
  });

  it("returns 401 invalid_credentials (same message) for non-existent email", async () => {
    const res = await login("nonexistent@example.com", "password");
    expect(res.status).toBe(401);
    expect(res.body).toEqual({
      error: "invalid_credentials",
      message: "Invalid credentials",
    });
  });

  it("returns 400 invalid_request for invalid body", async () => {
    const response = await fetch(`${baseUrl}/auth/login`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ email: "" }),
    });
    expect(response.status).toBe(400);
    const body = await response.json();
    expect(body).toEqual({
      error: "invalid_request",
      message: "Invalid request",
    });
  });
});
